source 'https://github.com/CocoaPods/Specs.git'  # 官方库
source 'http://dev.buluo-gs.com/gitlab/root/tribalc-ios-specs.git'   # 私有库
platform :ios, '8.0'
target ‘property’ do
pod 'TCCommonLibs'
pod 'YYText'
pod 'MBProgressHUD'
pod 'pop', '~> 1.0.7'
pod 'UITableView+FDTemplateLayoutCell'
pod 'MGSwipeTableCell', '~> 1.5.6'
pod 'AMap2DMap-NO-IDFA'
pod 'AMapSearch-NO-IDFA'
pod 'AMapLocation-NO-IDFA'
pod 'FLEX', '~> 2.0', :configurations => ['Debug']
pod 'Bugly'
end
